### ISSUE TITLE
Some svg attributes get lost

### ISSUE THREAD

**Issue by hennrunnel** [janjakubnanista/svg-to-jsx#5] opened 2016-02-15 08:05 UTC
Attributes of dashed svg like 'stroke-width="1.5"' and 'stroke-dasharray="4,5"' got deleted, although they could be transcribed as 'strokeWidth="1.5"'  and 'strokeDasharray="4.5"'

**Comment by janjakubnanista** [comment] 2016-02-15 12:23
Hi @hennrunnel! Could you provide an example of when this is happening? I tried it myself, I put a `stroke-width` attribute on an element (please excuse the minimalism of the example):

    <svg version="1.1">
        <text stroke-width="1.5"/>
    </svg>

and on the output I got:

    <svg version="1.1">
        <text strokeWidth="1.5"/>
    </svg>

which seems correct.

**Comment by hennrunnel** [comment] 2016-02-15 12:42
Hi! Here's the code of original svg:

`<svg width="22" height="2" viewBox="0 0 22 2" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <title>Line</title>
  <defs><path id="a" d="M0 1h23"/></defs>
  <g fill="none" fill-rule="evenodd">
    <use stroke="currentColor" stroke-width="1.5" stroke-dasharray="4,5" xlink:href="#a"/>
    <use xlink:href="#a"/>
  </g>
</svg>`

And here's the output:

'<svg height="2" width="22" viewBox="0 0 22 2">
	<defs>
		<path id="a" d="M0 1h23"/>
	</defs>
	<g fill="none">
		<path d="M0 1h23"/>
		<path d="M0 1h23"/>
	</g>
</svg>
'

**Comment by janjakubnanista** [comment] 2016-02-15 12:51
Ah there is a different problem - `<use/>` tags are not supported at the moment in React. I added an option that lets you replace these tags with what they reference.

However, I am only replacing the `<use/>` tag while discarding its attributes, that's the cause of this bug.

**Comment by hennrunnel** [comment] 2016-02-16 07:49
Thanks for clarifying! :+1:

**Comment by janjakubnanista** [comment] 2016-02-16 08:02
I am going to keep this open since I think the right thing to do is to merge attributes from the `<use/>` tag with the element that it references. I am going to check the SVG reference if this is what is supposed to happen.

**Comment by janjakubnanista** [comment] 2016-02-16 12:04
Fixed in 0.0.16

**Closed by janjakubnanista** 2016-02-16 12:04 UTC

**Comment by navidmesbah** [comment] 2016-11-01 07:42
same issue with stroke-linejoin letter-spacing and... despite the fact that there is no <use > attribute in the code...

**Comment by brandonwkipp** [comment] 2021-01-03 22:29
I'm seeing the same issue as @navidmesbah along with the attributes `stroke-miterlimit` & `stroke-linejoin`.

**Comment by fyodoriv** [comment] 2022-09-02 07:13
Having same issue with `clip-rule`
